Repository streamlink/streamlink, pull requests merged in 2019-11, with the labels that each got.

#2659 plugins.linelive: update to support VOD/archived streams
  docs/plugin_matrix.rst
  src/streamlink/plugins/linelive.py
Labels: plugin enhancement

#2671 plugins.vlive: Add support for V LIVE live streams
  docs/plugin_matrix.rst
  src/streamlink/plugins/vlive.py
  tests/plugins/test_vlive.py
Labels: new plugin, plugin request

#2652 stream.streamprocess: check that a process is usable before using it
  src/streamlink/stream/rtmpdump.py
  src/streamlink/stream/streamprocess.py
  tests/streams/test_stream_streamprocess.py
Labels: enhancement

#2698 plugin.api.useragents: update CHROME and FIREFOX User-Agent
  src/streamlink/plugin/api/useragents.py
Labels: enhancement

#2700 docs.cli: fix and reword the tutorial section
  docs/cli.rst
Labels: documentation, enhancement

#2705 stream.hls: Fix UnicodeDecodeError for log msg and name_prefix for stream_name
  src/streamlink/stream/hls.py
Labels: bug

#2692 plugins.twitch: fix API issue - 410 gone error
  src/streamlink/plugins/twitch.py
Labels: plugin issue

#2707 Release 1.3.0
  CHANGELOG.md
Labels: release
