Repository streamlink/streamlink, pull requests merged in 2020-10, with the labels that each got.

#3213 plugins.twitch: filter ads by EXT-X-DATERANGE tag
  src/streamlink/plugins/twitch.py
  src/streamlink/stream/hls_playlist.py
  tests/plugins/test_twitch.py
  tests/resources/hls/test_date.m3u8
  tests/streams/test_hls_playlist.py
Labels: plugin enhancement

#3220 plugins.twitch: remove platform access token param
  src/streamlink/plugins/twitch.py
Labels: plugin enhancement

#3223 plugins.twitch: fix metadata API response handling
  src/streamlink/plugins/twitch.py
  tests/plugins/test_twitch.py
Labels: plugin issue

#3204 docs: use recommonmark as an extension
  docs-requirements.txt
  docs/conf.py
Labels: dependency issue, documentation

#3230 ci: add python 3.9 test runners
  .codecov.yml
  .github/workflows/main.yml
Labels: continuous integration

#3216 plugins.srgssr: plugin removal
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/srgssr.py
  tests/plugins/test_srgssr.py
Labels: plugin removal

#3237 tests: fix early writer close in stream_hls mixin
  src/streamlink/stream/segmented.py
  tests/mixins/stream_hls.py
  tests/streams/test_hls.py
Labels: PR: merge commit, bug

#3236 docs: fix working tree check in deploy script
  script/deploy-docs.sh
Labels: continuous integration, documentation

#3244 docs: update plugin guidelines
  CONTRIBUTING.md
Labels: documentation

#3239 plugins.dlive: fix live playback
  src/streamlink/plugins/dlive.py
  tests/plugins/test_dlive.py
Labels: plugin issue

#3251 plugins.cbsnews: support for live streams from CBS News
  docs/plugin_matrix.rst
  src/streamlink/plugins/cbsnews.py
  tests/plugins/test_cbsnews.py
Labels: new plugin

#3243 plugins.livestream: remove AkamaiHDStream, use only secure HLSStream
  docs/plugin_matrix.rst
  src/streamlink/plugins/livestream.py
  tests/plugins/test_livestream.py
Labels: plugin issue

#3250 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/plugin_issue.md
  .github/ISSUE_TEMPLATE/plugin_request.md
  .github/issue_template.md
Labels: documentation

#3261 plugins.dingittv: removed, website is unmaintained
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/dingittv.py
  tests/plugins/test_dingittv.py
Labels: plugin removal

#3228 plugins.artetv: only pick the first variant of the stream
  src/streamlink/plugins/artetv.py
Labels: plugin enhancement, plugin issue

#3249 docs: add plugin addition/removal infos
  docs/developing.rst
Labels: documentation

#3262 plugins: mark some plugins as broken
  src/streamlink/plugins/btsports.py
  src/streamlink/plugins/cnews.py
  src/streamlink/plugins/ellobo.py
  src/streamlink/plugins/kingkong.py
  src/streamlink/plugins/nbcnews.py
  src/streamlink/plugins/skai.py
Labels: plugin issue

#3255 cli: make config based args available during early setup
  src/streamlink_cli/main.py
Labels: bug, enhancement

#3264 release: 1.7.0
  CHANGELOG.md
Labels: release

#3232 chore: drop support for Python 2
  .codecov.yml
  .github/workflows/main.yml
  docs/install.rst
  script/build-and-sign.sh
  script/install-dependencies.sh
  setup.cfg
  setup.py
  src/streamlink/session.py
Labels: python-2

#3269 chore: drop support for Python 3.5
  .codecov.yml
  .github/workflows/main.yml
  docs/install.rst
  setup.py
Labels: python-3

#3268 plugins.youtube: fix live playback
  src/streamlink/plugins/youtube.py
Labels: plugin issue

#3272 plugins.facebook: remove User-Agent
  src/streamlink/plugins/facebook.py
Labels: plugin issue

#3275 chore: remove old LIVESTREAMER_VERSION constant
  src/streamlink_cli/argparser.py
  src/streamlink_cli/constants.py
Labels: cleanup

#3273 logger: remove deprecated compat logger
  src/streamlink/logger.py
  src/streamlink/session.py
  src/streamlink_cli/console.py
  src/streamlink_cli/main.py
  tests/test_console.py
  tests/test_log.py
Labels: cleanup

#3277 chore: remove deprecated CLI arguments
  src/streamlink/plugins/btv.py
  src/streamlink/plugins/crunchyroll.py
  src/streamlink/plugins/pixiv.py
  src/streamlink/plugins/twitch.py
  src/streamlink/plugins/ustvnow.py
  src/streamlink/plugins/youtube.py
  src/streamlink/plugins/yupptv.py
  src/streamlink_cli/argparser.py
  src/streamlink_cli/main.py
Labels: cleanup

#3279 tests: fix log tests when run on a system with a non-UTC timezone
  dev-requirements.txt
  tests/test_log.py
Labels: bug

#3280 chore: use new py3 yield from syntax
  src/streamlink/plugin/api/mapper.py
  src/streamlink/plugins/abweb.py
  src/streamlink/plugins/app17.py
  src/streamlink/plugins/ard_live.py
  src/streamlink/plugins/artetv.py
  src/streamlink/plugins/atresplayer.py
  src/streamlink/plugins/bfmtv.py
  src/streamlink/plugins/bloomberg.py
  src/streamlink/plugins/brightcove.py
  src/streamlink/plugins/canalplus.py
  src/streamlink/plugins/cbsnews.py
  src/streamlink/plugins/ceskatelevize.py
  src/streamlink/plugins/clubbingtv.py
  src/streamlink/plugins/dailymotion.py
  src/streamlink/plugins/delfi.py
  src/streamlink/plugins/earthcam.py
  src/streamlink/plugins/facebook.py
  src/streamlink/plugins/filmon.py
  src/streamlink/plugins/gulli.py
  src/streamlink/plugins/idf1.py
  src/streamlink/plugins/ine.py
  src/streamlink/plugins/kugou.py
  src/streamlink/plugins/live_russia_tv.py
  src/streamlink/plugins/liveedu.py
  src/streamlink/plugins/livestream.py
  src/streamlink/plugins/lrt.py
  src/streamlink/plugins/mjunoon.py
  src/streamlink/plugins/mrtmk.py
  src/streamlink/plugins/okru.py
  src/streamlink/plugins/onetv.py
  src/streamlink/plugins/openrectv.py
  src/streamlink/plugins/picarto.py
  src/streamlink/plugins/pixiv.py
  src/streamlink/plugins/radiko.py
  src/streamlink/plugins/radionet.py
  src/streamlink/plugins/raiplay.py
  src/streamlink/plugins/rtbf.py
  src/streamlink/plugins/ruv.py
  src/streamlink/plugins/showroom.py
  src/streamlink/plugins/sportschau.py
  src/streamlink/plugins/svtplay.py
  src/streamlink/plugins/telefe.py
  src/streamlink/plugins/trt.py
  src/streamlink/plugins/trtspor.py
  src/streamlink/plugins/tv5monde.py
  src/streamlink/plugins/tvrby.py
  src/streamlink/plugins/tvrplus.py
  src/streamlink/plugins/ustvnow.py
  src/streamlink/plugins/vk.py
  src/streamlink/plugins/vrtbe.py
  src/streamlink/plugins/wasd.py
  src/streamlink/plugins/webtv.py
  src/streamlink/plugins/zeenews.py
  src/streamlink/plugins/zengatv.py
Labels: cleanup, python-3

#3278 plugins.picarto: explicitly detect and fail on private streams
  src/streamlink/plugins/picarto.py
Labels: plugin enhancement, plugin issue

#3286 docs: update wtwitch in thirdparty list
  docs/thirdparty.rst
Labels: documentation

#3294 ci.github: run lint step before test step
  .github/workflows/main.yml
Labels: continuous integration

#3301 plugins.twitch: player_type access token parameter
  src/streamlink/plugins/twitch.py
Labels: plugin issue

#3296 plugins.zdf_mediathek: also support 3sat mediathek
  src/streamlink/plugins/zdf_mediathek.py
  tests/plugins/test_zdf_mediathek.py
Labels: plugin enhancement

#3295 ci.github: install latest version of pynsist
  .github/workflows/main.yml
Labels: Windows installer, continuous integration

#3308 plugins.skai: plugin removal
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/skai.py
  tests/plugins/test_skai.py
Labels: plugin removal

#3299 plugins.trt/trtspor: remove plugins
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/trt.py
  src/streamlink/plugins/trtspor.py
  tests/plugins/test_trt.py
  tests/plugins/test_trtspor.py
Labels: plugin removal

#3307 chore: implicit py3 super() calls
  src/streamlink/plugin/api/validate.py
  src/streamlink/plugins/abematv.py
  src/streamlink/plugins/abweb.py
  src/streamlink/plugins/albavision.py
  src/streamlink/plugins/atresplayer.py
  src/streamlink/plugins/btsports.py
  src/streamlink/plugins/dlive.py
  src/streamlink/plugins/filmon.py
  src/streamlink/plugins/mitele.py
  src/streamlink/plugins/nicolive.py
  src/streamlink/plugins/openrectv.py
  src/streamlink/plugins/pixiv.py
  src/streamlink/plugins/reuters.py
  src/streamlink/plugins/steam.py
  src/streamlink/plugins/streamme.py
  src/streamlink/plugins/streann.py
  src/streamlink/plugins/tvplayer.py
  src/streamlink/plugins/tvrby.py
  src/streamlink/plugins/twitcasting.py
  src/streamlink/plugins/twitch.py
  src/streamlink/plugins/ustreamtv.py
  src/streamlink/plugins/ustvnow.py
  src/streamlink/plugins/wwenetwork.py
  src/streamlink/plugins/youtube.py
  src/streamlink/plugins/yupptv.py
  src/streamlink/plugins/zattoo.py
  src/streamlink/stream/dash.py
  src/streamlink/stream/dash_manifest.py
  src/streamlink/stream/ffmpegmux.py
  src/streamlink/stream/file.py
  src/streamlink/stream/hls.py
  src/streamlink/stream/hls_filtered.py
  src/streamlink/stream/streamprocess.py
  src/streamlink_cli/output.py
  tests/mixins/stream_hls.py
  tests/plugins/test_twitch.py
  tests/streams/test_hls.py
  tests/streams/test_hls_filtered.py
Labels: cleanup, python-3

#3309 plugins.kingkong: plugin removal
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/kingkong.py
  tests/plugins/test_kingkong.py
Labels: plugin issue, plugin removal

#3311 chore: remove u-strings
  src/streamlink/plugins/abematv.py
  src/streamlink/plugins/artetv.py
  src/streamlink/plugins/crunchyroll.py
  src/streamlink/plugins/cubetv.py
  src/streamlink/plugins/dogan.py
  src/streamlink/plugins/euronews.py
  src/streamlink/plugins/gardenersworld.py
  src/streamlink/plugins/nicolive.py
  src/streamlink/plugins/onetv.py
  src/streamlink/plugins/rtve.py
  src/streamlink/plugins/steam.py
  src/streamlink/plugins/tamago.py
  src/streamlink/plugins/webtv.py
  src/streamlink/stream/dash_manifest.py
  src/streamlink/stream/hls.py
  src/streamlink/utils/l10n.py
  src/streamlink_cli/argparser.py
  src/streamlink_cli/console.py
  src/streamlink_cli/constants.py
  src/streamlink_cli/main.py
  src/streamlink_cli/output.py
  tests/plugins/test_albavision.py
  tests/plugins/test_tvplayer.py
  tests/plugins/testplugin.py
  tests/test_api_http_session.py
  tests/test_api_validate.py
  tests/test_cli_playerout.py
  tests/test_cmdline_title.py
  tests/test_utils.py
Labels: cleanup, python-3

#3312 ci.github: set ubuntu to 20.04 and python to 3.9
  .github/workflows/main.yml
Labels: continuous integration

#3293 plugins.cnews: fix video ID search, add schema
  src/streamlink/plugins/cnews.py
  tests/plugins/test_cnews.py
Labels: plugin issue

#3305 plugins.ellobo: plugin removal
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/ellobo.py
  tests/plugins/test_ellobo.py
Labels: plugin removal

#3306 plugins.nbcnews: fix video ID search, add schemas
  src/streamlink/plugins/nbcnews.py
Labels: plugin issue

#3313 cli: optional player-args input variable
  src/streamlink_cli/argparser.py
  src/streamlink_cli/constants.py
  src/streamlink_cli/output.py
  tests/test_cli_main.py
  tests/test_cli_playerout.py
Labels: enhancement
