Repository streamlink/streamlink, pull requests merged in 2020-12, with the labels that each got.

#3385 plugins.pluto: ignore invalid channels
  src/streamlink/plugins/pluto.py
Labels: plugin issue

#3382 docs: fix CLI page
  docs/cli.rst
Labels: documentation

#3379 docs: split CLI args in HTML output into rows
  docs/_themes/sphinx_rtd_theme_violet/static/css/theme.css
  docs/ext_argparse.py
Labels: documentation

#3383 plugins.filmon: mitigate for non-JSON data response
  src/streamlink/plugins/filmon.py
Labels: plugin enhancement, plugin issue

#3366 session: replace usage of deprecated imp module
  src/streamlink/session.py
  src/streamlink/utils/__init__.py
  tests/plugins/testplugin_invalid.py
  tests/plugins/testplugin_missing.py
  tests/plugins/testplugin_override.py
  tests/test_plugins.py
  tests/test_session.py
Labels: cleanup

#3390 refactor: test_session, move testplugin files
  tests/plugin/testplugin.py
  tests/plugin/testplugin_invalid.py
  tests/plugin/testplugin_missing.py
  tests/plugin/testplugin_override.py
  tests/plugin/testplugin_support.py
  tests/test_cmdline.py
  tests/test_plugins_input.py
  tests/test_session.py
  tests/test_streamlink_api.py
Labels: cleanup

#3398 plugin.api: remove support_plugin
  src/streamlink/plugin/api/__init__.py
  src/streamlink/plugin/api/support_plugin.py
  tests/plugin/testplugin.py
  tests/plugin/testplugin_support.py
  tests/test_session.py
Labels: cleanup

#3399 tests: fix test_cmdline{,_title}
  tests/test_cmdline.py
Labels: bug, tests

#3405 cli.output: replace MPV player title parameter
  src/streamlink_cli/output.py
  tests/test_cli_playerout.py
  tests/test_cmdline_title.py
Labels: enhancement, player issue

#3394 plugins: fix radiko.py url
  src/streamlink/plugins/radiko.py
  tests/plugins/test_radiko.py
Labels: plugin issue, restriction: geo blocked

#3410 stream.dash: allow '_alt' streams with the same resolution
  src/streamlink/stream/dash.py
  tests/resources/dash/test_10.mpd
  tests/streams/test_dash.py
  tests/streams/test_dash_parser.py
Labels: PR: squash commits, stream: DASH

#3408 plugins.afreeca: update '_get_channel_info' with 'bno', plugin cleanup
  src/streamlink/plugins/afreeca.py
Labels: cleanup, plugin enhancement, plugin issue

#3415 stream.hls: merge hls_filtered with hls
  src/streamlink/plugins/afreeca.py
  src/streamlink/plugins/twitch.py
  src/streamlink/session.py
  src/streamlink/stream/hls.py
  src/streamlink/stream/hls_filtered.py
  src/streamlink/stream/segmented.py
  src/streamlink_cli/argparser.py
  tests/streams/test_hls_filtered.py
Labels: stream: HLS

#3413 stream.ffmpegmux: disable -start_at_zero for -copyts as default
  src/streamlink/plugins/facebook.py
  src/streamlink/session.py
  src/streamlink/stream/ffmpegmux.py
  src/streamlink_cli/argparser.py
  src/streamlink_cli/main.py
  tests/streams/test_ffmpegmux.py
Labels: stream: ffmpegmux

#3404 add ffmpeg-copyts option
  src/streamlink/session.py
  src/streamlink/stream/ffmpegmux.py
  src/streamlink_cli/argparser.py
  src/streamlink_cli/main.py
  tests/streams/test_ffmpegmux.py
Labels: stream: ffmpegmux

#3419 cli: move --stream-url to different args group
  src/streamlink_cli/argparser.py
Labels: documentation

#3422 cache: catch OverflowError in set()
  src/streamlink/cache.py
  tests/test_cache.py
Labels: bug

#3423 docs: fix link in readme
  README.md
Labels: documentation

#3425 add --niconico-timeshift-offset option to the nicolive plugin
  src/streamlink/plugins/nicolive.py
Labels: plugin enhancement

#3424 plugins.dogan: fix/update
  docs/plugin_matrix.rst
  src/streamlink/plugins/dogan.py
  tests/plugins/test_dogan.py
Labels: plugin issue

#3428 plugins.youtube: Fix 'ytInitialData' for channel pages
  src/streamlink/plugins/youtube.py
Labels: plugin issue

#3409 release: 2.0.0
  CHANGELOG.md
Labels: release

#3442 tools: force LF line endings via .gitattributes
  .gitattributes
  .github/workflows/main.yml
  tests/plugins/test_vk.py
  tests/plugins/test_webcast_india_gov.py
Labels: cleanup, continuous integration

#3450 cli.main: use *_args, **_kwargs for create_http_server
  src/streamlink_cli/main.py
Labels: PR: squash commits, enhancement

#3427 docs: add minimalist code of conduct
  CODE_OF_CONDUCT.md
Labels: meta

#3434 plugins.Nicolive: login before getting wss api url
  src/streamlink/plugins/nicolive.py
Labels: plugin enhancement

#3456 docs: remove outdated gst-player example
  docs/api_guide.rst
  examples/gst-player.py
Labels: cleanup, documentation

#3457 plugins.mico: plugin removal
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/mico.py
  tests/plugins/test_mico.py
Labels: plugin removal

#3461 plugins.twitch: fix access_token on invalid inputs
  src/streamlink/plugins/twitch.py
Labels: plugin issue

#3420 ci: add netlify docs preview deploy config
  .editorconfig
  netlify.toml
Labels: continuous integration, documentation

#3464 docs: add thank-you section to index page
  docs/index.rst
Labels: documentation

#3459 build: include man page in wheels
  .github/workflows/main.yml
  setup.py
Labels: documentation, packages

#3463 docs: bump furo docs req to 2020.12.28.beta23
  docs-requirements.txt
Labels: documentation
