Repository streamlink/streamlink, pull requests merged in 2021-03, with the labels that each got.

#3600 plugins: fix and update removed plugins list
  docs/developing.rst
  script/update-removed-plugins.sh
  src/streamlink/plugins/.removed
  tests/test_plugins_meta.py
Labels: Windows installer, bug

#3611 docs: add appimages section to install docs
  docs/install.rst
Labels: documentation

#3621 ci.netlify: build docs when CHANGELOG.md changes
  netlify.toml
Labels: continuous integration, documentation

#3618 docs: add pip to packages lists
  docs/install.rst
Labels: documentation

#3617 plugins.abematv: Fixed download problem.
  src/streamlink/plugins/abematv.py
Labels: plugin issue, restriction: geo blocked

#3619 cli.output: fix named pipe player input on Windows
  src/streamlink_cli/output.py
  tests/test_cmdline_player_fifo.py
Labels: bug, os: Windows

#3637 plugin.api: update useragents
  src/streamlink/plugin/api/useragents.py
Labels: enhancement

#3635 plugins.zattoo: use 'dash' as default stream
  src/streamlink/plugins/zattoo.py
Labels: plugin issue

#3636 plugins.btsports: remove plugin
  docs/plugin_matrix.rst
  src/streamlink/plugins/.removed
  src/streamlink/plugins/btsports.py
  tests/plugins/test_btsports.py
Labels: plugin removal

#3627 plugins.rtpplay: add schema and fix HLS URL
  src/streamlink/plugins/rtpplay.py
Labels: plugin issue

#3620 release: 2.1.0
  CHANGELOG.md
Labels: release

#3645 build: don't build sdist/bdist quietly
  script/build-and-sign.sh
Labels: continuous integration

#3644 build: include removed plugins file in sdist
  MANIFEST.in
Labels: bug, packages

#3648 release: 2.1.1
  CHANGELOG.md
Labels: release
