Repository streamlink/streamlink, pull requests merged in 2021-01, with the labels that each got.

#3470 2021
  LICENSE
  docs/conf.py
  src/streamlink/__init__.py
Labels: meta

#3479 http_session: remove HTTPAdapterWithReadTimeout
  src/streamlink/plugin/api/http_session.py
Labels: cleanup

#3471 plugins.bfmtv : fix rmcstory and rmcdecouverte
  src/streamlink/plugins/bfmtv.py
Labels: plugin issue

#3481 plugins.facebook: Add 'Log into Facebook' error message.
  src/streamlink/plugins/facebook.py
Labels: plugin enhancement

#3485 plugins.dogus: remove channel and update test
  docs/plugin_matrix.rst
  src/streamlink/plugins/dogus.py
  tests/plugins/test_dogus.py
Labels: plugin issue

#3484 plugins.turkuvaz: add channels and URL tests
  src/streamlink/plugins/turkuvaz.py
  tests/plugins/test_turkuvaz.py
Labels: plugin enhancement

#3487 docs: improve install-via-pip section
  docs/install.rst
Labels: documentation

#3495 docs: fix description of `--ffmpeg-fout`
  src/streamlink_cli/argparser.py
Labels: documentation

#3502 docs: update URL to Fedora repo
  docs/install.rst
Labels: documentation

#3510 build: include man page in sdist tarballs
  MANIFEST.in
Labels: enhancement, packages

#3518 utils/l10n: fix langs without alpha_2 in pycountry
  src/streamlink/utils/l10n.py
  tests/test_localization.py
Labels: bug

#3505 plugins.twitcasting: add support for private/password-protected streams
  src/streamlink/plugins/twitcasting.py
Labels: PR: squash commits, plugin enhancement

#3514 plugins.bloomberg: fix and refactor plugin
  src/streamlink/plugins/bloomberg.py
Labels: plugin issue

#3486 utils: remove custom memoize decorator
  src/streamlink/plugins/wwenetwork.py
  src/streamlink/session.py
  src/streamlink/utils/__init__.py
  tests/test_session.py
Labels: cleanup

#3499 docs: remove CLI tutorial from man page
  docs/_man.rst
  docs/conf.py
Labels: documentation

#3503 plugins.oneplusone: site changes: fix iframe url pattern
  src/streamlink/plugins/oneplusone.py
Labels: plugin issue

#3506 plugins.stadium: adaptions for new player api
  src/streamlink/plugins/stadium.py
Labels: plugin issue
