Repository streamlink/streamlink, pull requests merged in 2022-11, with the labels that each got.

#4924 tests: fix plugins metadata encoding
  tests/test_plugins.py
Labels: bug, tests

#4928 chore: fix new mypy warnings and errors
  src/streamlink/plugin/api/websocket.py
  src/streamlink/plugins/ustreamtv.py
  src/streamlink/stream/ffmpegmux.py
  src/streamlink/stream/hls.py
  src/streamlink_cli/main.py
Labels: cleanup

#4930 tools: move list of files to mypy config
  .github/workflows/lint.yml
  pyproject.toml
  src/streamlink_cli/compat.py
Labels: continuous integration, tools, typing

#4929 docs: add mypy for code linting
  docs/developing.rst
Labels: documentation, typing

#4932 docs: add code style section
  docs/developing.rst
Labels: documentation

#4940 docs: fix twitch oauth token header name
  docs/cli/plugins/twitch.rst
Labels: documentation, PR: needs commit message fix

#4936 stream.hls: add more debug messages to write calls
  src/streamlink/stream/hls.py
Labels: stream: HLS

#4950 build: add urllib3 directly and set it to >=1.26.0
  setup.cfg
  src/streamlink/plugin/api/http_session.py
  src/streamlink/plugin/api/http_session.pyi
  tests/test_api_http_session.py
Labels: dependencies, build config

#4952 plugins.twitch: add --twitch-access-token-param
  docs/cli/plugins/twitch.rst
  src/streamlink/plugins/twitch.py
Labels: plugin enhancement

#4954 plugins.vtvgo: update to get required cookies
  src/streamlink/plugins/vtvgo.py
Labels: plugin issue

#4941 logger: add new log level "all"
  src/streamlink/logger.py
  src/streamlink_cli/argparser.py
  tests/test_logger.py
Labels: logging

#4959 docs: fix and update man page
  docs/_man.rst
Labels: documentation

#4963 cli: fix log format for log level "all"
  src/streamlink_cli/main.py
Labels: logging, CLI

#4967 plugins.tv8: filter out ad segments
  src/streamlink/plugins/tv8.py
Labels: plugin enhancement

#4927 release: 5.1.0
  CHANGELOG.md
Labels: release

#4971 docs: add missing urllib3 to install page
  docs/install.rst
Labels: documentation, dependencies

#4972 stream.segmented: properly close StreamIO
  src/streamlink/stream/segmented.py
  tests/mixins/stream_hls.py
Labels: bug, stream: segmented

#4976 stream: add FilteredStream and abstract filtering
  src/streamlink/stream/filtered.py
  src/streamlink/stream/hls.py
  tests/stream/test_hls_filtered.py
Labels: stream: HLS, API: stream

#4977 plugin.api.websocket: use certifi's cacert.pem
  docs/install.rst
  setup.cfg
  src/streamlink/plugin/api/websocket.py
  tests/test_api_websocket.py
Labels: dependencies, API: websocket

#4989 ci.github: temporarily downgrade Sphinx to 5.2.3
  .github/workflows/main.yml
Labels: bug, documentation, dependencies

#4970 docs: add pipx install info
  docs/install.rst
Labels: documentation

#4990 release: 5.1.1
  CHANGELOG.md
Labels: release

#4991 docs: fix changelog of 5.1.1 release
  CHANGELOG.md
Labels: documentation

#4995 docs: fix man page links in HTML docs
  .github/workflows/main.yml
  docs/Makefile
  docs/conf.py
Labels: bug, documentation, dependencies

#4997 plugins.tvp: fix channel ID lookup
  src/streamlink/plugins/tvp.py
  tests/plugins/test_tvp.py
Labels: plugin issue

#4998 stream.ffmpegmux: abort on ValueError during read
  src/streamlink/stream/ffmpegmux.py
Labels: bug, stream: ffmpegmux

#4994 plugins.svtplay: rewrite plugin and add HLS
  src/streamlink/plugins/svtplay.py
Labels: plugin issue, restriction: geo blocked
