Repository streamlink/streamlink, pull requests merged in 2024-10, with the labels that each got.

#6213 docs: update example plugins
  README.md
  docs/index.rst
Labels: documentation

#6212 release: 6.11.0
  CHANGELOG.md
Labels: release

#6220 utils.module: add override parameter
  src/streamlink/session/plugins.py
  src/streamlink/utils/module.py
  tests/utils/test_module.py
Labels: bug

#6221 tools: ignore typing refactor commits in git-blame
  .git-blame-ignore-revs
Labels: tools

#6223 session: fix --interface on custom HTTPAdapters
  src/streamlink/session/options.py
  tests/session/test_options.py
Labels: bug

#6225 cli: fix help text of --output and --record
  src/streamlink_cli/argparser.py
Labels: CLI

#6227 cli: deprecate --verbose-player and --fifo
  docs/deprecations.rst
  src/streamlink_cli/argparser.py
  src/streamlink_cli/main.py
Labels: documentation, cleanup, CLI

#6231 ci.github: remove -dev suffix from py313 runners
  .github/workflows/test.yml
Labels: continuous integration, python: 3.13

#6052 docs: drop i686 Linux AppImages and x86+py38 Windows builds
  docs/install.rst
Labels: documentation

#6149 cli: remove deprecated {,plugin-}config paths
  docs/cli/config.rst
  src/streamlink_cli/constants.py
  src/streamlink_cli/main.py
  tests/cli/main/test_setup_config_args.py
Labels: CLI, breaking change

#6196 cli: remove deprecated --force-progress argument
  src/streamlink_cli/argparser.py
  src/streamlink_cli/main.py
  tests/cli/main/test_output_stream.py
Labels: CLI, breaking change

#6235 docs: add migration docs for the breaking changes of 7.0.0
  docs/deprecations.rst
  docs/migrations.rst
Labels: documentation, breaking change

#6236 docs: restore plugin sideloading path on Windows
  docs/cli/plugin-sideloading.rst
Labels: documentation

#6239 cli: fix errors on missing stdin fd
  src/streamlink_cli/argparser.py
  src/streamlink_cli/console.py
  src/streamlink_cli/main.py
  tests/cli/main/test_check_file_output.py
  tests/cli/test_argparser.py
  tests/cli/test_console.py
Labels: bug, CLI

#6242 plugins.tv3cat: update plugin matchers
  src/streamlink/plugins/tv3cat.py
  tests/plugins/test_tv3cat.py
Labels: plugin issue

#6244 build: bump trio dependency to >=0.25,<1
  pyproject.toml
Labels: bug, dependencies

#6248 tools: bump ruff to 0.6.9 and mypy to 1.12.0
  dev-requirements.txt
  src/streamlink/stream/hls/hls.py
Labels: tools

#6249 cli: keep values of deprecated plugin arguments
  src/streamlink_cli/argparser.py
  tests/cli/test_argparser.py
Labels: CLI

#6247 plugins.afreeca: rename to soop
  src/streamlink/plugins/soop.py
  tests/plugins/test_soop.py
Labels: plugin issue

#6250 docs: rewrite 7.0.0 migrations
  docs/migrations.rst
Labels: documentation, breaking change

#6251 cli.output: remove VLC stream metadata variables
  src/streamlink_cli/output/player.py
  tests/cli/output/test_player.py
Labels: bug, player issue, CLI

#6253 cli.argparser: remove VLC --title var escape logic
  src/streamlink_cli/argparser.py
Labels: documentation, CLI

#6256 validate: move from streamlink.plugin.api package
  docs/api/validate.rst
  docs/api_guide/validate.rst
  src/streamlink/plugin/api/validate.py
  src/streamlink/validate/__init__.py
  src/streamlink/validate/_exception.py
  src/streamlink/validate/_schemas.py
  src/streamlink/validate/_validate.py
  src/streamlink/validate/_validators.py
  src/streamlink/webbrowser/chromium.py
  tests/test_validate.py
Labels: API: validate

#6257 plugins.soop: refactor plugin and fix issues
  src/streamlink/plugins/soop.py
  tests/plugins/test_soop.py
Labels: plugin issue

#6259 tools: bump ruff to 0.7.0 and mypy to 1.12.1
  dev-requirements.txt
  src/streamlink/stream/hls/hls.py
Labels: tools

#6261 tools: ignore ruff format commit in git-blame
  .git-blame-ignore-revs
Labels: tools

#6262 plugins.ruv: rewrite and fix plugin
  src/streamlink/plugins/ruv.py
  tests/plugins/test_ruv.py
Labels: plugin issue

#6267 logger: mark basicConfig kwargs as kw-only
  src/streamlink/logger.py
  src/streamlink_cli/main.py
Labels: logging

#6269 ci.readthedocs: update fetch depth with tags
  .readthedocs.yml
Labels: continuous integration
