Repository streamlink/streamlink, pull requests merged in 2024-02, with the labels that each got.

#5810 utils.parse: fix import path
  src/streamlink/utils/parse.py
Labels: cleanup

#5811 tools: bump ruff to 0.2.0 and update config
  dev-requirements.txt
  pyproject.toml
Labels: tools

#5816 ci.github: bump setup-python action to v5
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/useragents.yml
Labels: continuous integration

#5818 docs: add 6.6.0 deprecations
  docs/deprecations.rst
  src/streamlink/session/session.py
Labels: documentation

#5819 docs: fix custom ext_argparse Sphinx extension
  docs/_man.rst
  docs/cli.rst
  docs/ext_argparse.py
  script/build-shell-completions.sh
  src/streamlink_cli/_parser.py
  src/streamlink_cli/main.py
Labels: documentation, CLI

#5823 docs: fix scrollbars in sidebars
  docs/_static/styles/custom.css
Labels: documentation

#5822 session: implement lazy plugins loading
  src/streamlink/session/plugins.py
  src/streamlink/session/session.py
  src/streamlink/utils/module.py
  src/streamlink_cli/_parser.py
  src/streamlink_cli/main.py
  tests/cli/test_main.py
  tests/conftest.py
  tests/session/test_plugins.py
  tests/session/test_session.py
Labels: API: session

#5829 options: fix Argument typing information
  src/streamlink/options.py
  src/streamlink/plugin/plugin.py
Labels: typing

#5830 tools: bump ruff to 0.2.1 and fix issues
  dev-requirements.txt
  pyproject.toml
Labels: tools

#5831 ci.github: bump setup-python action to v5
  .github/workflows/test.yml
Labels: continuous integration

#5835 stream.hls: add hlsstream keyword to MuxedHLSStream
  src/streamlink/stream/hls/hls.py
Labels: stream: HLS

#5839 release: 6.6.1
  CHANGELOG.md
Labels: release

#5840 tools: bump ruff to 0.2.2 and fix issues
  dev-requirements.txt
  pyproject.toml
  tests/cli/output/test_player.py
  tests/cli/utils/test_player.py
  tests/plugins/test_wwenetwork.py
  tests/utils/test_path.py
Labels: cleanup, tools

#5842 build: bump setuptools to >=65.6
  docs/install.rst
  pyproject.toml
Labels: dependencies, build config

#5844 session: fix missing plugin override log message
  src/streamlink/session/plugins.py
  tests/session/test_plugins.py
Labels: bug, API: session

#5847 plugins.afreeca: fix broadcast number regex
  src/streamlink/plugins/afreeca.py
Labels: plugin issue

#5851 release: 6.6.2
  CHANGELOG.md
Labels: release

#5854 plugins.vimeo: fix missing HLS/DASH API results
  src/streamlink/plugins/vimeo.py
Labels: plugin issue

#5858 plugins.ltv_lsm_lv: fix plugin, rm LTVHLSStream
  src/streamlink/plugins/ltv_lsm_lv.py
  tests/plugins/test_ltv_lsm_lv.py
Labels: plugin issue, restriction: geo blocked

#5861 stream.hls: fix maps with and without keys
  src/streamlink/stream/hls/hls.py
  src/streamlink/stream/hls/m3u8.py
  src/streamlink/stream/hls/segment.py
  tests/stream/hls/test_hls.py
Labels: bug, stream: HLS

#5852 plugins.mangomolo: new plugin
  src/streamlink/plugins/mangomolo.py
  tests/plugins/test_mangomolo.py
Labels: new plugin

#5865 cli: only log args with the same dest once
  src/streamlink_cli/main.py
Labels: CLI

#5869 plugins.bloomberg: refactor and fix data regex
  src/streamlink/plugins/bloomberg.py
  tests/plugins/test_bloomberg.py
Labels: plugin issue

#5871 tools: bump ruff to 0.3.0 and fix issues
  .github/workflows/lint.yml
  dev-requirements.txt
  src/streamlink/session/http.pyi
Labels: tools
