Repository streamlink/streamlink, pull requests merged in 2024-05, with the labels that each got.

#5981 docs: update Windows builds flavors
  docs/_static/styles/custom.css
  docs/install.rst
Labels: documentation

#5985 docs: fix deprecated ruff <path> call
  docs/developing.rst
Labels: documentation

#5987 build: only require exceptiongroup on py<3.11
  docs/install.rst
  pyproject.toml
  src/streamlink/compat.py
  src/streamlink/plugins/twitch.py
  src/streamlink/webbrowser/webbrowser.py
  tests/webbrowser/cdp/test_client.py
  tests/webbrowser/cdp/test_connection.py
  tests/webbrowser/test_webbrowser.py
Labels: dependencies

#5731 plugins.chzzk: new plugin
  src/streamlink/plugins/chzzk.py
  tests/plugins/test_chzzk.py
Labels: new plugin, disallowed plugin type

#5990 build: fix encoding when reading plugin files
  build_backend/plugins_json.py
Labels: bug, os: Windows, build config

#5991 release: 6.7.4
  CHANGELOG.md
Labels: release

#5983 plugins.tf1: implement authentication
  src/streamlink/plugins/tf1.py
Labels: plugin issue

#5999 tools: bump mypy to 1.10.0 and bump ruff to 0.4.4
  dev-requirements.txt
Labels: tools

#6003 tools: bump ruff to 0.4.5 and fix issues
  dev-requirements.txt
  pyproject.toml
Labels: tools

#6002 plugins.chzzk: live detail api response validation error fix
  src/streamlink/plugins/chzzk.py
Labels: plugin issue

#6005 plugins: officially deprecate re-exports
  docs/deprecations.rst
  src/streamlink/plugins/__init__.py
  tests/plugin/testplugin.py
  tests/test_plugins.py
Labels: cleanup

#6011 plugins.welt: fix validation schema
  src/streamlink/plugins/welt.py
Labels: plugin issue
